apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
  namespace: j12t-alpha
data:
  IdentifyService.yml: |
    dev: False
    n_threads: 16
    host: "0.0.0.0"
    port: "8080"
    debug: true
    threaded: True
    use_reloader: False
    identify_channel: "vehicleidentify-identify.j12t-alpha.svc.cluster.local:32050"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicleidentify-webserver
  labels:
    app: vehicleidentify-webserver
  namespace: j12t-alpha
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: vehicleidentify-webserver
  - port: 9126
    targetPort: 9126
    name: telegraf
  type: NodePort
  selector:
    app: vehicleidentify-webserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vehicleidentify-webserver
  namespace: j12t-alpha
spec:
  selector:
    matchLabels:
      app: vehicleidentify-webserver
  serviceName: vehicleidentify-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicleidentify-webserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: vehicleidentify-webserver
        image: jerapiblannett/vehicleidentify-webserver:latest
        env:
        - name: VEHICLE_IDENTIFICATION_LOGFILE
          value: ./log/webserver.log
        - name: VIDGEAR_LOGFILE
          value: ./log/webserver.log
        ports:
        - containerPort: 32050
        volumeMounts:
        - name: vehicleidentify-storage
          mountPath: "/usr/run/VehicleIdentification"
          subPath: data
        - name: vehicleidentify-storage
          mountPath: "/usr/run/VehicleIdentification"
          subPath: log
        - name: webserver-config
          mountPath: "/usr/run/VehicleIdentification/config"
      - name: telegraf-agent
        image: telegraf:1.20
        ports:
        - containerPort: 9126
        volumeMounts:
        - name: telegraf-config
          mountPath: "/etc/telegraf"
      volumes:
      - name: vehicleidentify-storage
        persistentVolumeClaim:
          claimName: vehicleidentify-claim
      - name: telegraf-config
        configMap:
          name: telegraf-config
          defaultMode: 420
      - name: webserver-config
        configMap:
          name: webserver-config
          defaultMode: 420