apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-config
  namespace: j12t-alpha
data:
  YoloService.yml: |
    insecure_ports:
      - "[::]:32052"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicleidentify-yolo
  labels:
    app: vehicleidentify-yolo
  namespace: j12t-alpha
spec:
  ports:
  - port: 32052
    targetPort: 32052
    # nodePort: 32052
    name: vehicleidentify-yolo
  - port: 9126
    targetPort: 9126
    name: telegraf
  type: NodePort
  selector:
    app: vehicleidentify-yolo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vehicleidentify-yolo
  namespace: j12t-alpha
spec:
  selector:
    matchLabels:
      app: vehicleidentify-yolo
  serviceName: vehicleidentify-yolo
  replicas: 2
  template:
    metadata:
      labels:
        app: vehicleidentify-yolo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: vehicleidentify-yolo
        image: jerapiblannett/vehicleidentify-yolo:latest
        ports:
        - containerPort: 32052
        volumeMounts:
        - name: yolo-config
          mountPath: "/usr/run/VehicleIdentification/config"
      - name: telegraf-agent
        image: telegraf:1.20
        ports:
        - containerPort: 9126
        volumeMounts:
        - name: telegraf-config
          mountPath: "/etc/telegraf"
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
          defaultMode: 420
      - name: yolo-config
        configMap:
          name: yolo-config
          defaultMode: 420