services:
  imgcolor:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.imgcolor
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/imgcolor.log
    ports:
      - 50055:50055
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  imgresize:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.imgresize
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/imgresize.log
    ports:
      - 50051:50051
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  platecrop:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.platecrop
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/platecrop.log
    ports:
      - 50053:50053
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  yolo:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.yolo
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/yolo.log
    ports:
      - 50052:50052
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  ocr:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.ocr
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./ocr.log
    ports:
      - 50054:50054
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  identify:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.identify
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/identify.log
    ports:
      - 50000:50000
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  webserver:
    restart: on-failure:5
    build:
      context: ..
      dockerfile: ./docker/dockerfile.webserver
      network: host
    # network_mode: host
    environment:
      - VEHICLE_IDENTIFICATION_LOGFILE=./log/webserver.log
      - VIDGEAR_LOGFILE:./log/webserver.log
    ports:
      - 8080:8080
    volumes:
      - ..\config:/usr/run/VehicleIdentification/config
      - ..\log:/usr/run/VehicleIdentification/log
      - ..\data:/usr/run/VehicleIdentification/data
  # vehicleidentification_main:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/dockerfile.vehicleIdeitification
  #   volumes:
  #     - D:\tmp\vehicle-identification:/usr/run/VehicleIdentification/data
  #   network_mode: host